version: '3.8'

services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server/users.db:/app/users.db
      - ./server/server.log:/app/server.log
      - ./server:/app
    environment:
      - DB_PATH=/app/users.db

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    depends_on:
      - server
    volumes:
      - ./bot/favorites.json:/app/favorites.json
      - ./bot/watchlist.json:/app/watchlist.json
      - ./bot/collections.json:/app/collections.json
      - ./bot/bot.log:/app/bot.log
      - ./bot:/app
    environment:
      - SERVER_URL=http://server:8000