services:
  botervice:
    stop_grace_period: 30s
    stop_signal: SIGTERM
    container_name: bot-api
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  bot-data:
  pgadmin-data:

networks:
  postgres:
    driver: bridge